### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by LunaSare** [LunaSare/datelifeMS1#4]
- [x] 1. Create summary ages table for table 2
- [x] 2. Update tables of figure of all Fringillidae, add to Supplementary data
- [x] 3. update figure 5, especially points of source ages, identify which ones were used and which ones were excluded.
- [x] 4. Choose one figure to showcase results of cross validation analyses
- [x] 5. Add other cross validation figures to supplements
- [ ] 6. Check that cross validation is run without chronograms from the same study, especially for study from Price etal. 2014, chronogram 2
- [x] 7. Address remaining comments
- [x] 8. Submit!!!
